#!/usr/bin/env python3
"""Generate the `sigil chat` banner mark: the logo rendered as truecolor
half-blocks (▀), emitted as rich markup so rich downsamples to the terminal's
color depth. Writes the jac glob into src/sigil_logo.jac and a faithful PNG
preview to /tmp. Regenerate with: python3 .github/scripts/gen_banner_logo.py
"""
import math
import pathlib

from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parents[2]
BG = (13, 13, 22)          # the panel/terminal ground the mark composites onto
WIDTH = 20                 # columns; rows = height/2


def bold_mark(S=480):
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    cx = cy = S / 2
    R = S * 0.40
    hexpts = [(cx + R * math.cos(math.radians(a)), cy + R * math.sin(math.radians(a)))
              for a in (270, 330, 30, 90, 150, 210)]
    V, VS, C = (167, 139, 250, 255), (139, 92, 246, 255), (56, 189, 248, 255)
    tri = [(cx + R * 0.52 * math.cos(math.radians(a)), cy + R * 0.52 * math.sin(math.radians(a)))
           for a in (270, 30, 150)]
    d.polygon(tri, fill=(56, 189, 248, 70))
    d.line(tri + [tri[0]], fill=C, width=int(S * 0.024), joint="curve")
    for x, y in hexpts:
        d.line([(x, y), (cx, cy)], fill=VS, width=int(S * 0.020))
    d.line(hexpts + [hexpts[0]], fill=V, width=int(S * 0.034), joint="curve")
    nr = S * 0.048
    for x, y in hexpts:
        d.ellipse([x - nr, y - nr, x + nr, y + nr], fill=V)
    cr = S * 0.078
    d.ellipse([cx - cr, cy - cr, cx + cr, cy + cr], fill=C)
    return img.crop(img.getbbox())


def comp(px):
    r, g, b, a = px
    if a < 40:
        return None
    f = a / 255
    return (round(r * f + BG[0] * (1 - f)),
            round(g * f + BG[1] * (1 - f)),
            round(b * f + BG[2] * (1 - f)))


def hexs(c):
    return "#%02x%02x%02x" % c


def main():
    mark = bold_mark()
    h = round(mark.height * WIDTH / mark.width)
    if h % 2:
        h += 1
    im = mark.resize((WIDTH, h), Image.LANCZOS)
    px = im.load()
    rows = h // 2

    # faithful preview PNG (each cell = 16x32, top/bottom halves) on BG
    cw, ch = 16, 32
    prev = Image.new("RGB", (WIDTH * cw, rows * ch), BG)
    pd = ImageDraw.Draw(prev)

    lines = []
    for yc in range(rows):
        parts = []
        for x in range(WIDTH):
            t = comp(px[x, yc * 2])
            b = comp(px[x, yc * 2 + 1])
            X, Y = x * cw, yc * ch
            if t:
                pd.rectangle([X, Y, X + cw - 1, Y + ch // 2 - 1], fill=t)
            if b:
                pd.rectangle([X, Y + ch // 2, X + cw - 1, Y + ch - 1], fill=b)
            if t and b:
                parts.append(f"[{hexs(t)} on {hexs(b)}]▀[/]")
            elif t:
                parts.append(f"[{hexs(t)}]▀[/]")
            elif b:
                parts.append(f"[{hexs(b)}]▄[/]")
            else:
                parts.append(" ")
        lines.append("".join(parts))
    prev.save("/tmp/banner_final.png")

    # emit the jac module: a glob list of rich-markup rows
    body = ["\"\"\"Generated by .github/scripts/gen_banner_logo.py — the SigilAgent mark",
            "as truecolor half-blocks (rich markup; rich downsamples per terminal).",
            "Do not hand-edit; rerun the generator.\"\"\"", "",
            "glob BANNER_LOGO: list = ["]
    for ln in lines:
        esc = ln.replace("\\", "\\\\").replace('"', '\\"')
        body.append(f'    "{esc}",')
    body.append("];")
    (ROOT / "src" / "sigil_logo.jac").write_text("\n".join(body) + "\n")
    print(f"wrote src/sigil_logo.jac ({WIDTH}x{rows}) + /tmp/banner_final.png")


if __name__ == "__main__":
    main()
